/*\file
 *
 * \brief LUT for factorial and related functions (header)
*/


/**************************************************************
THIS FILE IS GENERATED VIA SCRIPTS. IF YOU WANT
EVERYONE TO STAY SANE, DO NOT EDIT THIS FILE DIRECTLY

Generated via:
    ../../scripts/generate_factorial.py Factorial_LUT
**************************************************************/


#ifndef _GUARD_FACTORIAL_LUT_HPP_
#define _GUARD_FACTORIAL_LUT_HPP_


#include <cstdint>



namespace bpmodule {
namespace math {
namespace lut {



extern uint64_t fac_int_lut_[21];
static const int FAC_INT_LUT_MAX_ = 20;      // Maximum index of fac_int

extern float fac_float_lut_[35];
static const int FAC_FLOAT_LUT_MAX_ = 34;      // Maximum index of fac_float

extern double fac_double_lut_[171];
static const int FAC_DOUBLE_LUT_MAX_ = 170;      // Maximum index of fac_double

extern uint64_t dfac_int_lut_[35];
static const int DFAC_INT_LUT_MAX_ = 34;      // Maximum index of dfac_int

extern float dfac_float_lut_[58];
static const int DFAC_FLOAT_LUT_MAX_ = 57;      // Maximum index of dfac_float

extern double dfac_double_lut_[302];
static const int DFAC_DOUBLE_LUT_MAX_ = 301;      // Maximum index of dfac_double

extern uint64_t dfac_2nm1_int_lut_[18];
static const int DFAC_2NM1_INT_LUT_MAX_ = 17;      // Maximum index of dfac_2nm1_int

extern float dfac_2nm1_float_lut_[29];
static const int DFAC_2NM1_FLOAT_LUT_MAX_ = 28;      // Maximum index of dfac_2nm1_float

extern double dfac_2nm1_double_lut_[151];
static const int DFAC_2NM1_DOUBLE_LUT_MAX_ = 150;      // Maximum index of dfac_2nm1_double




} // closing namespace lut
} // closing namespace math
} // closing namespace bpmodule



#endif
