language: cpp
sudo: required

#Blocklist
branches:
  except:
  - gh-pages

############################################
# On Ubuntu g++ packages are named g++-X.Y #
############################################

#TODO: loop over values of X and Y

matrix:
  env:
    - PY_EXE=python3.5 CXX_COMPILER='g++-4.9'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
      - deadsnakes
    packages:
      - python3.5
      - cmake
      - cmake-data
      - libdb-dev
      - g++-4.9
      - libmpich1.0-dev
script:
- cd ${HOME}
###################################################
# Build Eigen because CMake doesn't support https #
###################################################
- wget http://bitbucket.org/eigen/eigen/get/3.3.2.tar.bz2
- tar -xf 3.3.2.tar.bz2
- cd eigen-eigen-da9b4e14c255
- cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
                    -DCMAKE_BUILD_TYPE=Release
                    -DCMAKE_INSTALL_PREFIX=${HOME}
- cd build && make install

#####################################
#Build Pulsar-Meta for dependencies #
#####################################

#TODO: investigate TravisCI cache-ing
- git clone https://github.com/pulsar-chem/Pulsar-Meta.git
- cd Pulsar-Meta
- cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
                    -DMPI_CXX_COMPILER=mpicxx
                    -DMPI_C_COMPILER=mpicc
                    -DCMAKE_BUILD_TYPE=Release
                    -DCMAKE_INSTALL_PREFIX=${HOME}
                    -DCMAKE_PREFIX_PATH=${HOME}
                    -DPYTHON_EXECUTABLE=${PY_EXE}
                    -DENABLE_PULSAR=False
- cd build && make install

#####################
#Build Pulsar-Core  #
#####################
- cd ${TRAVIS_BUILD_DIR}
- cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
                    -DCMAKE_BUILD_TYPE=Release
                    -DMPI_CXX_COMPILER=mpicxx
                    -DMPI_C_COMPILER=mpicc
                    -DPYTHON_EXECUTABLE=${PY_EXE}
                    -DCMAKE_PREFIX_PATH=${HOME}
                    -DCMAKE_INSTALL_RPATH=${HOME}
- cd build && make
- ctest
- cd -

before_install:
##################################################
# Decode the rsa key so Travis can SSH to GitHub #
##################################################
- openssl aes-256-cbc
  -K $encrypted_92294f6245f4_key
  -iv $encrypted_92294f6245f4_iv
  -in scripts/travisci_rsa.enc
  -out scripts/travisci_rsa
  -d
- chmod 0600 scripts/travisci_rsa
- cp scripts/travisci_rsa ~/.ssh/id_rsa

install:
- sudo apt-get install --yes doxygen graphviz

after_failure:
- cat Testing/Temporary/LastTest.log

after_success:
########################################################
# Build the documentation and commit it back to GitHub #
########################################################
- scripts/publish-doxygen.sh
