language: cpp
sudo: required

#Blocklist
branches:
  except:
  - gh-pages

#TODO: other compilers/python
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - cmake
        - cmake-data
        - g++-4.9
        - libdb-dev
        - libmpich1.0-dev
    env: CXX_COMPILER='g++-4.9'

script:
- cd ${HOME}
- ls
#####################################
#Build Pulsar-Meta for dependencies #
#####################################

#TODO: investigate TravisCI cache-ing
- git clone https://github.com/pulsar-chem/Pulsar-Meta.git
- cd Pulsar-Meta
- cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
                    -DMPI_CXX_COMPILER=mpicxx
                    -MPI_C_COMPILER=mpicc
                    -DCMAKE_BUILD_TYPE=Release
                    -DCMAKE_INSTALL_PREFIX=${HOME}
                    -DPYTHON_EXECUTABLE=python3
                    -DENABLE_PULSAR=False
- cd build && make install
#####################
#Build Pulsar-Core  #
#####################
- cd ${TRAVIS_BUILD_DIR}
- cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
                    -DCMAKE_BUILD_TYPE=Release
                    -DMPI_CXX_COMPILER=mpicxx
                    -MPI_C_COMPILER=mpicc
                    -DPYTHON_EXECUTABLE=python3
                    -DCMAKE_PREFIX_PATH=${HOME}
                    -DCMAKE_INSTALL_RPATH=${HOME}
- cd build && make
- ctest
- cd -

before_install:
##################################################
# Decode the rsa key so Travis can SSH to GitHub #
##################################################
- openssl aes-256-cbc
  -K $encrypted_92294f6245f4_key
  -iv $encrypted_92294f6245f4_iv
  -in scripts/travisci_rsa.enc
  -out scripts/travisci_rsa
  -d
- chmod 0600 scripts/travisci_rsa
- cp scripts/travisci_rsa ~/.ssh/id_rsa
install:
- cmake -version
- sudo apt-get install --yes doxygen graphviz
after_failure:
- cat Testing/Temporary/LastTest.log
after_success:
- scripts/publish-doxygen.sh
