language: cpp
sudo: required

#Blocklist
branches:
  except:
  - gh-pages

#TODO: Other compilers

matrix:
  env:
    - PY_VER=3.5 CXX_COMPILER='g++-4.9'

before_install:
##################################################
# Decode the rsa key so Travis can SSH to GitHub #
##################################################
- openssl aes-256-cbc
  -K $encrypted_92294f6245f4_key
  -iv $encrypted_92294f6245f4_iv
  -in scripts/travisci_rsa.enc
  -out scripts/travisci_rsa
  -d
- chmod 0600 scripts/travisci_rsa
- cp scripts/travisci_rsa ~/.ssh/id_rsa
- sudo add-apt-repository ppa:ubuntu-toolchain-r-test
- sudo add-apt-repository ppa:george-edison55-precise-backports
- sudo apt-get update

install:
- sudo apt-get install --yes doxygen graphviz cmake cmake-data libdb-dev g++-4.9 libmpich1.0-dev
- cd ${HOME}
#####################################
# Get Miniconda for python versions #
#####################################
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=3.5
- source activate test-environment
- cd ${HOME}
###################################################
# Build Eigen because CMake doesn't support https #
###################################################
- wget http://bitbucket.org/eigen/eigen/get/3.3.2.tar.bz2
- tar -xf 3.3.2.tar.bz2
- cd eigen-eigen-da9b4e14c255
- cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=g++-4.9 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${HOME}
- cd build && make install

#####################################
#Build Pulsar-Meta for dependencies #
#####################################
- git clone https://github.com/pulsar-chem/Pulsar-Meta.git
- cd Pulsar-Meta
- cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=g++-4.9 -DMPI_CXX_COMPILER=mpicxx -DMPI_C_COMPILER=mpicc -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${HOME} -DCMAKE_PREFIX_PATH=${HOME} -DPYTHON_EXECUTABLE=python3 -DENABLE_PULSAR=False
- cd build && make install

script:
#####################
#Build Pulsar-Core  #
#####################
- cd ${TRAVIS_BUILD_DIR}
- cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=g++-4.9 -DCMAKE_BUILD_TYPE=Release -DMPI_CXX_COMPILER=mpicxx -DMPI_C_COMPILER=mpicc -DPYTHON_EXECUTABLE=python3 -DCMAKE_PREFIX_PATH=${HOME} -DCMAKE_INSTALL_RPATH=${HOME}
- cd build && make
- ctest
- cd -

after_failure:
- cat Testing/Temporary/LastTest.log

after_success:
########################################################
# Build the documentation and commit it back to GitHub #
########################################################
- scripts/publish-doxygen.sh
