language: cpp
sudo: required
branches:
  except:
  - gh-pages
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - cmake
        - cmake-data
        - g++-4.9
    env: CXX_COMPILER='g++-4.9'
before_install:
- openssl aes-256-cbc 
  -K $encrypted_92294f6245f4_key 
  -iv $encrypted_92294f6245f4_iv
  -in scripts/travisci_rsa.enc 
  -out scripts/travisci_rsa 
  -d
- chmod 0600 scripts/travisci_rsa
- cp scripts/travisci_rsa ~/.ssh/id_rsa
install:
- cmake -version
- sudo apt-get install --yes doxygen graphviz
script:
- cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_BUILD_TYPE=Release
- cd build && make
- ctest
- cd -
after_failure:
- cat Testing/Temporary/LastTest.log
after_success:
- scripts/publish-doxygen.sh
