language: cpp
sudo: required

#Blocklist
branches:
  except:
  - gh-pages

#TODO: Other compilers

matrix:
  env:
    - PY_VER=3.5 CXX_COMPILER='g++-4.9'

#################################################################
# The below commands are run for each entry of the build matrix #
#################################################################

################################################################
# Apt dependencies.  Doing it this way loads them from images. #
################################################################
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - graphviz
      - cmake
      - cmake-data
      - libdb-dev
      - g++-4.9
      - libmpich1.0-dev

before_install: #This step is meant to gather dependencies
##################################################
# Decode the rsa key so Travis can SSH to GitHub #
##################################################
- openssl aes-256-cbc
  -K $encrypted_92294f6245f4_key
  -iv $encrypted_92294f6245f4_iv
  -in .travis/travisci_rsa.enc
  -out .travis/travisci_rsa
  -d
- chmod 0600 .travis/travisci_rsa
- cp .travis/travisci_rsa ~/.ssh/id_rsa
- .travis/build_depends.sh "4.9" "3.5"

install: #This step is meant to build the project to be tested
#####################
#Build Pulsar-Core  #
#####################
- cd ${TRAVIS_BUILD_DIR}
- cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=g++-4.9
                    -DCMAKE_BUILD_TYPE=Release
                    -DMPI_CXX_COMPILER=mpicxx
                    -DMPI_C_COMPILER=mpicc
                    -DPYTHON_EXECUTABLE=${HOME}/miniconda/envs/test-environment/bin/python
                    -DCMAKE_PREFIX_PATH=${HOME}
                    -DCMAKE_INSTALL_RPATH=${HOME}/lib
- cd build && make

script: #This step is meant to test the built project
- ctest

after_failure:
- cat Testing/Temporary/LastTest.log

after_success:
########################################################
# Build the documentation and commit it back to GitHub #
########################################################
- cd -
- .travis/publish-doxygen.sh
