/*\file
 *
 * \brief LUTs for Atomic Information (header)
*/


/**************************************************************
THIS FILE IS GENERATED VIA SCRIPTS. IF YOU WANT
EVERYONE TO STAY SANE, DO NOT EDIT THIS FILE DIRECTLY

Generated via:
    ../../scripts/generate_atomicinfo.py AtomicInfo_LUT

CREATED: 2015-11-13 22:27:46.002584
**************************************************************/


#ifndef _GUARD_ATOMICINFO_LUT_HPP_
#define _GUARD_ATOMICINFO_LUT_HPP_


#include <map>
#include "bpmodule/molecule/AtomicInfo.hpp"
#include "bpmodule/util/StringUtil.hpp"



namespace bpmodule {
namespace molecule {
namespace lut {



//////////////////////////////////////////////////
// Various data maps. Stored in LUT source file
//////////////////////////////////////////////////
extern const std::map<int, std::string> atomic_Z_sym_;

extern const std::map<std::string, int, util::CaseInsensitiveCompare> atomic_sym_Z_;

extern const std::map<int, AtomicData> atomic_Z_data_;




} // closing namespace lut
} // closing namespace molecule
} // closing namespace bpmodule



#endif
