#ifndef _GUARD_PYBIND11_HPP_
#define _GUARD_PYBIND11_HPP_

#include "bpmodule/pragma.h"

PRAGMA_WARNING_PUSH
PRAGMA_WARNING_IGNORE_SHADOW
PRAGMA_WARNING_IGNORE_EXTRA_SEMICOLON
PRAGMA_WARNING_IGNORE_SWITCH_MISSING_DEFAULT
#include "pybind11/pybind11.h"
PRAGMA_WARNING_POP

#endif
