/*\file
 *
 * \brief LUTs for Atomic Information (header)
*/


/**************************************************************
THIS FILE IS GENERATED VIA SCRIPTS. IF YOU WANT
EVERYONE TO STAY SANE, DO NOT EDIT THIS FILE DIRECTLY

Generated via:
    ../../scripts/generate_atomicinfo.py AtomicInfo_LUT

CREATED: 2016-01-27 17:44:47.238271
**************************************************************/


#ifndef BPMODULE_GUARD_SYSTEM__ATOMICINFO_LUT_HPP_
#define BPMODULE_GUARD_SYSTEM__ATOMICINFO_LUT_HPP_


#include <map>
#include "bpmodule/system/AtomicInfo.hpp"
#include "bpmodule/util/StringUtil.hpp"



namespace bpmodule {
namespace system {
namespace lut {



//////////////////////////////////////////////////
// Various data maps. Stored in LUT source file
//////////////////////////////////////////////////
extern const std::map<int, std::string> atomic_Z_sym_;

extern const std::map<std::string, int, util::CaseInsensitiveCompare> atomic_sym_Z_;

extern const std::map<int, AtomicData> atomic_Z_data_;




} // closing namespace lut
} // closing namespace system
} // closing namespace bpmodule



#endif
