# Adds a core library target
macro(ADD_CORELIB LIB_NAME
                  LIB_FILES
                  ADD_CXX_FLAGS
                  ADD_CXX_LINK_FLAGS
                  ADD_CXX_INCLUDES)

  set(CMAKE_SHARED_MODULE_PREFIX_OLD ${CMAKE_SHARED_MODULE_PREFIX})
  set(CMAKE_SHARED_MODULE_PREFIX "")

  message(STATUS "Adding core ${LIB_NAME}")
  add_library(${LIB_NAME} OBJECT ${LIB_FILES})

  # CXX Flags
  list(APPEND ${LIB_NAME}_CXX_FLAGS "${BPMODULE_CXX_FLAGS}")
  list(APPEND ${LIB_NAME}_CXX_FLAGS "-fPIC")
  list(APPEND ${LIB_NAME}_CXX_FLAGS "${ADD_CXX_FLAGS}")
  string(REPLACE ";" " " ${LIB_NAME}_CXX_FLAGS "${${LIB_NAME}_CXX_FLAGS}")
  message(STATUS "${LIB_NAME} cxx compile flags: ${${LIB_NAME}_CXX_FLAGS}")
  set_target_properties(${LIB_NAME} PROPERTIES COMPILE_FLAGS "${${LIB_NAME}_CXX_FLAGS}")

  # Includes
  list(APPEND ${LIB_NAME}_CXX_INCLUDES "${BPMODULE_CXX_INCLUDES}")
  list(APPEND ${LIB_NAME}_CXX_INCLUDES "${Boost_INCLUDE_DIRS}")
  list(APPEND ${LIB_NAME}_CXX_INCLUDES "${PYTHON_INCLUDE_DIRS}")
  list(APPEND ${LIB_NAME}_CXX_INCLUDES "${ADD_CXX_INCLUDES}")
  message(STATUS "${LIB_NAME} cxx includes: ${${LIB_NAME}_CXX_INCLUDES}")
  set_target_properties(${LIB_NAME} PROPERTIES INCLUDE_DIRECTORIES "${${LIB_NAME}_CXX_INCLUDES}")

  # Linker flags
  list(APPEND ${LIB_NAME}_CXX_LINK_FLAGS "${BPMODULE_CXX_LINK_FLAGS}")
  list(APPEND ${LIB_NAME}_CXX_LINK_FLAGS "${Boost_LIBRARIES}")
  list(APPEND ${LIB_NAME}_CXX_LINK_FLAGS "${PYTHON_LIBRARIES_LIBRARIES}")
  list(APPEND ${LIB_NAME}_CXX_LINK_FLAGS "${ADD_CXX_LINK_FLAGS}")
  message(STATUS "${LIB_NAME} cxx link flags: ${${LIB_NAME}_CXX_LINK_FLAGS}")

  set(CMAKE_SHARED_MODULE_PREFIX ${CMAKE_SHARED_MODULE_PREFIX_OLD})

endmacro()
