if("${CMAKE_CXX_COMPILER_ID}" MATCHES "Intel")
    list(APPEND BPMODULE_CXX_STRICT_FLAGS "-fPIC")
    list(APPEND BPMODULE_CXX_STRICT_FLAGS "-std=c++11")
    list(APPEND BPMODULE_CXX_STRICT_FLAGS "-w3")
elseif("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU")
    list(APPEND BPMODULE_CXX_STRICT_FLAGS "-fPIC")
    list(APPEND BPMODULE_CXX_STRICT_FLAGS "-std=c++11")
    list(APPEND BPMODULE_CXX_STRICT_FLAGS "-Wextra;-Wshadow;-Wall;-pedantic;")
endif()

message(STATUS "Strict flags: ${BPMODULE_CXX_STRICT_FLAGS}")

