/*! \file
 *
 * \brief Various constants and conversion factors (header)
*/


/**************************************************************
THIS FILE IS GENERATED VIA SCRIPTS. IF YOU WANT
EVERYONE TO STAY SANE, DO NOT EDIT THIS FILE DIRECTLY

Generated via:
    ../scripts/generate_constants.py constants

CREATED: 2016-04-24 10:41:14.432562
**************************************************************/


#ifndef PULSAR_GUARD_PULSAR__CONSTANTS_H_
#define PULSAR_GUARD_PULSAR__CONSTANTS_H_


/*! \brief Angstrom (in m)
 *
 */
#define ANGSTROM_SI     1.0e-10


/*! \brief Joule -> Hartree relationship (E_H)
 *
 * NIST CODATA 2014
 */
#define ATOMIC_UNIT_ENERGY     2.293712317e+17


/*! \brief Bohr radius (AU of length) in m
 *
 * NIST CODATA 2014
 */
#define ATOMIC_UNIT_LENGTH     5.2917721067e-11


/*! \brief Mass of electron in kg
 *
 * NIST CODATA 2014
 */
#define ATOMIC_UNIT_MASS     9.10938356e-31


/*! \brief Atomic unit of time (in s)
 *
 * NIST CODATA_2014
 */
#define ATOMIC_UNIT_TIME     2.418884326509e-17


/*! \brief Atomic unit of velocity (in m/s)
 *
 * NIST CODATA_2014
 */
#define ATOMIC_UNIT_VELOCITY     2.18769126277e+6


/*! \brief Atomic unit of time (in s)
 *
 * NIST CODATA_2014
 */
#define AU_TIME_SI     2.418884326509e-17


/*! \brief Atomic unit of velocity (in m/s)
 *
 * NIST CODATA_2014
 */
#define AU_VELOCITY_SI     2.18769126277e+6


/*! \brief Avogadro's constant (mol^-1)
 *
 * NIST CODATA 2014
 */
#define AVOGADROS_CONSTANT     6.022140857e+23


/*! \brief Bohr radius (AU of length) in A
 *
 * NIST CODATA 2014
 */
#define BOHR_RADIUS_ANGSTROMS     5.2917721067e-1


/*! \brief Bohr radius (AU of length) in m
 *
 * NIST CODATA 2014
 */
#define BOHR_RADIUS_SI     5.2917721067e-11


/*! \brief Boltzmann's constant in eV/K
 *
 * NIST CODATA 2014
 */
#define BOLTZMANN_CONSTANT_EV_K     8.6173303e-5


/*! \brief Boltzmann's constant in J/K
 *
 * NIST CODATA 2014
 */
#define BOLTZMANN_CONSTANT_SI     1.38064852e-23


/*! \brief Mass of electron in kg
 *
 * NIST CODATA 2014
 */
#define ELECTRON_MASS_SI     9.10938356e-31


/*! \brief Hartree -> Joule relationship (J)
 *
 * NIST CODATA 2014
 */
#define HARTREE_TO_JOULE     4.35974465e-18


/*! \brief Joule -> eV relationship (eV)
 *
 * NIST CODATA 2014
 */
#define JOULE_TO_EV     6.241509126e+18


/*! \brief Joule -> Hartree relationship (E_H)
 *
 * NIST CODATA 2014
 */
#define JOULE_TO_HARTREE     2.293712317e+17


/*! \brief 1/pi
 *
 */
#define ONE_OVER_PI     3.18309886183790672e-1


/*! \brief 1/sqrt(pi)
 *
 */
#define ONE_OVER_SQRT_PI     5.64189583547756287e-1


/*! \brief The famous pi
 *
 * mmm pie
 */
#define PI     3.14159265358979324


/*! \brief pi^2
 *
 */
#define PI_SQUARED     9.86960440108935862


/*! \brief h/(2pi)
 *
 * NIST CODATA 2014
 */
#define PLANCK_HBAR_SI     1.0545718e-34


/*! \brief Planck's constant in J*s
 *
 * NIST CODATA 2014
 */
#define PLANCK_H_SI     6.62607004e-34


/*! \brief Speed of light in atomic units
 *
 * Derived from NIST CODATA 2014
 */
#define SPEED_OF_LIGHT_AU     1.37035999138384034e+2


/*! \brief Speed of light in m/s
 *
 * NIST CODATA 2014
 */
#define SPEED_OF_LIGHT_SI     2.99792458e+8


/*! \brief sqrt(pi)
 *
 */
#define SQRT_PI     1.77245385090551603


/*! \brief 2*pi
 *
 */
#define TWO_PI     6.28318530717958648





#endif
